# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.security.authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        public: false
        autowire: true

    user_new_handler:
            class: AppBundle\User\Handler\CreateUserHandler
            autowire: true

    user_edit_handler:
            class: AppBundle\User\Handler\EditUserHandler
            autowire: true

    user_delete_handler:
        class: AppBundle\User\Handler\DeleteUserHandler
        autowire: true

    user_doctrine:
        class: AppBundle\User\Query\DoctrineUsers
        autowire: true

